name: Daniel Lowengrub
markdown: kramdown
kramdown:
  toc_levels: [1,2]
  parse_block_html: true
highlighter: rouge
permalink: /blog/:year/:month/:day/:title
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
